### ISSUE TITLE
possible typo in "synchronize" notification

### ISSUE THREAD

**Issue by SimJoSt** [TkTech/notifico#168] opened 2017-03-05 23:12 UTC
We just got the notification:

    [$REPO] $USER synchronize pull request #$NUMBER: $COMMIT  - $LINK

Shouldn't it be "synchronize**d**"? Past tense? Like all the other notifications?
Or is this on purpose?

**Comment by TkTech** [comment] 2017-03-06 00:53
Nope, it's a typo :)

**Comment by nyuszika7h** [comment] 2017-03-06 22:16
This is not a bug in Notifico. It's GitHub's fault. Though it may be worth fixing this on display, as they said they won't fix it (at least until the next major API version) as it would be an API-breaking change.

**Comment by SimJoSt** [comment] 2020-02-16 12:53
@TkTech @nyuszika7h did Github resolve this in the last years?^^  
Or did you do some work on your own code to mitigate it?

**Comment by nyuszika7h** [comment] 2020-02-16 13:08
Nope, it's still `synchronize` on GitHub's side.

**Closed** 2022-11-02 08:38 UTC
Labels: bug, hook
